# The URL the site will be built for
base_url = "https://www.trebetherick.net"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false
generate_sitemap = true
generate_robots_txt = true

taxonomies = [{ name = "tags", feed = true }]

# The site title and description; used in feeds by default.
title = "The Trebetherick Museum"
description = "A community-built website chronicalling the history of the village of Trebetherick, Cornwall, UK."

# The default language; used in feeds.
default_language = "en"

# The site theme to use.
theme = "seagull"

feed_filenames = ["atom.xml", "rss.xml"]

author = "The Oaten family & Trebetherick residents and friends"

generate_feeds = true

[markdown]
insert_anchor_links = "heading"
bottom_footnotes = true
smart_punctuation = true
render_emoji = true
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true
highlight_theme = "visual-studio-dark"


[extra.nav]
links = ["houses.md", "farms.md", "stenodoc.md", "area.md", "about.md"]

[[extra.links]]
title = "ğŸ¡ Houses"
url = "/houses"

[[extra.links]]
title = "ğŸ‘ Farms"
url = "/farms"

[[extra.links]]
title = "â›ª St Enodoc Church"
url = "/stenodoc"

[[extra.links]]
title = "ğŸŒ³ Local Area"
url = "/area"

[[extra.links]]
title = "â“ About"
url = "/about"


[[extra.links]]

# the following links will appear in the footer
[[extra.social.link]]
name = "Github"
url = "https://github.com/0atman/trebetherick.net/tree/main/content"
img = "https://cdn.simpleicons.org/github/FFF"

[extra]
# Put all your custom variables here
#theme = "superhero"
email = "contact@trebetherick.net"
name = "Trebetherick.net"
logo = "img/gull.svg"
description = "The Trebetherick Museum"

#schemes = ""
